namespace UltimateEnd.SaveFile.CHD
{
    public enum ChdrError
    {
        CHDERR_NONE = 0,
        CHDERR_NO_INTERFACE,
        CHDERR_OUT_OF_MEMORY,
        CHDERR_INVALID_FILE,
        CHDERR_INVALID_PARAMETER,
        CHDERR_INVALID_DATA,
        CHDERR_FILE_NOT_FOUND,
        CHDERR_REQUIRES_PARENT,
        CHDERR_FILE_NOT_WRITEABLE,
        CHDERR_READ_ERROR,
        CHDERR_WRITE_ERROR,
        CHDERR_CODEC_ERROR,
        CHDERR_INVALID_PARENT,
        CHDERR_HUNK_OUT_OF_RANGE,
        CHDERR_DECOMPRESSION_ERROR,
        CHDERR_COMPRESSION_ERROR,
        CHDERR_CANT_CREATE_FILE,
        CHDERR_CANT_VERIFY,
        CHDERR_NOT_SUPPORTED,
        CHDERR_METADATA_NOT_FOUND,
        CHDERR_INVALID_METADATA_SIZE,
        CHDERR_UNSUPPORTED_VERSION,
        CHDERR_VERIFY_INCOMPLETE,
        CHDERR_CODEC_INIT,
        CHDERR_WALKING_PARENT
    }
}